name: Setup
description: Common environment setup

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - uses: actions/cache@v4
      id: cache
      with:
        path: '**/node_modules'
        key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'