name: WIP
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-wip:
    runs-on: ubuntu-latest
    steps:
      - name: WIP Check
        uses: wip/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}